server:
  port: 8001

spring:
  application:
    name: spring-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19941224

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiangchao.springcloud.entities

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl